package com.patelki.domain;

import java.util.Date;

public class TnMAddressType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_address_type.address_type_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer addressTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_address_type.address_type
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String addressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_address_type.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_address_type.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_address_type.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_address_type.address_type_id
     *
     * @return the value of tn_m_address_type.address_type_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getAddressTypeId() {
        return addressTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_address_type.address_type_id
     *
     * @param addressTypeId the value for tn_m_address_type.address_type_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setAddressTypeId(Integer addressTypeId) {
        this.addressTypeId = addressTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_address_type.address_type
     *
     * @return the value of tn_m_address_type.address_type
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_address_type.address_type
     *
     * @param addressType the value for tn_m_address_type.address_type
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType == null ? null : addressType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_address_type.status
     *
     * @return the value of tn_m_address_type.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_address_type.status
     *
     * @param status the value for tn_m_address_type.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_address_type.created_by
     *
     * @return the value of tn_m_address_type.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_address_type.created_by
     *
     * @param createdBy the value for tn_m_address_type.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_address_type.created_date
     *
     * @return the value of tn_m_address_type.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_address_type.created_date
     *
     * @param createdDate the value for tn_m_address_type.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}