package com.patelki.domain;

import java.util.Date;

public class TnMEducation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_education.education_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer educationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_education.education
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_education.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_education.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_education.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_education.education_id
     *
     * @return the value of tn_m_education.education_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getEducationId() {
        return educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_education.education_id
     *
     * @param educationId the value for tn_m_education.education_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setEducationId(Integer educationId) {
        this.educationId = educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_education.education
     *
     * @return the value of tn_m_education.education
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_education.education
     *
     * @param education the value for tn_m_education.education
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_education.status
     *
     * @return the value of tn_m_education.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_education.status
     *
     * @param status the value for tn_m_education.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_education.created_by
     *
     * @return the value of tn_m_education.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_education.created_by
     *
     * @param createdBy the value for tn_m_education.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_education.created_date
     *
     * @return the value of tn_m_education.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_education.created_date
     *
     * @param createdDate the value for tn_m_education.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}