package com.patelki.domain;

import java.util.Date;

public class TnMLevelManagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_level_management.level_management_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer levelManagementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_level_management.level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String levelManagement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_level_management.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_level_management.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_level_management.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_level_management.level_management_id
     *
     * @return the value of tn_m_level_management.level_management_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getLevelManagementId() {
        return levelManagementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_level_management.level_management_id
     *
     * @param levelManagementId the value for tn_m_level_management.level_management_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setLevelManagementId(Integer levelManagementId) {
        this.levelManagementId = levelManagementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_level_management.level_management
     *
     * @return the value of tn_m_level_management.level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getLevelManagement() {
        return levelManagement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_level_management.level_management
     *
     * @param levelManagement the value for tn_m_level_management.level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setLevelManagement(String levelManagement) {
        this.levelManagement = levelManagement == null ? null : levelManagement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_level_management.status
     *
     * @return the value of tn_m_level_management.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_level_management.status
     *
     * @param status the value for tn_m_level_management.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_level_management.created_by
     *
     * @return the value of tn_m_level_management.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_level_management.created_by
     *
     * @param createdBy the value for tn_m_level_management.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_level_management.created_date
     *
     * @return the value of tn_m_level_management.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_level_management.created_date
     *
     * @param createdDate the value for tn_m_level_management.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}