package com.patelki.domain;

import java.util.Date;

public class TnMReligion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_religion.religion_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer religionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_religion.religion
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String religion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_religion.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_religion.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn_m_religion.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_religion.religion_id
     *
     * @return the value of tn_m_religion.religion_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getReligionId() {
        return religionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_religion.religion_id
     *
     * @param religionId the value for tn_m_religion.religion_id
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setReligionId(Integer religionId) {
        this.religionId = religionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_religion.religion
     *
     * @return the value of tn_m_religion.religion
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_religion.religion
     *
     * @param religion the value for tn_m_religion.religion
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setReligion(String religion) {
        this.religion = religion == null ? null : religion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_religion.status
     *
     * @return the value of tn_m_religion.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_religion.status
     *
     * @param status the value for tn_m_religion.status
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_religion.created_by
     *
     * @return the value of tn_m_religion.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_religion.created_by
     *
     * @param createdBy the value for tn_m_religion.created_by
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn_m_religion.created_date
     *
     * @return the value of tn_m_religion.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn_m_religion.created_date
     *
     * @param createdDate the value for tn_m_religion.created_date
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}