package com.patelki.domain;

import java.util.Date;

public class TnMCard {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_card.card_id
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private Integer cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_card.card
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private String card;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_card.status
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_card.created_by
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_card.created_date
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private Date createdDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_card.card_id
	 * @return  the value of tn_m_card.card_id
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public Integer getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_card.card_id
	 * @param cardId  the value for tn_m_card.card_id
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_card.card
	 * @return  the value of tn_m_card.card
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public String getCard() {
		return card;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_card.card
	 * @param card  the value for tn_m_card.card
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setCard(String card) {
		this.card = card == null ? null : card.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_card.status
	 * @return  the value of tn_m_card.status
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_card.status
	 * @param status  the value for tn_m_card.status
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_card.created_by
	 * @return  the value of tn_m_card.created_by
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_card.created_by
	 * @param createdBy  the value for tn_m_card.created_by
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_card.created_date
	 * @return  the value of tn_m_card.created_date
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_card.created_date
	 * @param createdDate  the value for tn_m_card.created_date
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
}