package com.patelki.domain;

import java.util.Date;

public class TnMRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_role.role_id
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_role.role
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_role.status
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_role.created_by
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private Integer createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tn_m_role.created_date
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	private Date createdDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_role.role_id
	 * @return  the value of tn_m_role.role_id
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_role.role_id
	 * @param roleId  the value for tn_m_role.role_id
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_role.role
	 * @return  the value of tn_m_role.role
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_role.role
	 * @param role  the value for tn_m_role.role
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_role.status
	 * @return  the value of tn_m_role.status
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_role.status
	 * @param status  the value for tn_m_role.status
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_role.created_by
	 * @return  the value of tn_m_role.created_by
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_role.created_by
	 * @param createdBy  the value for tn_m_role.created_by
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tn_m_role.created_date
	 * @return  the value of tn_m_role.created_date
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tn_m_role.created_date
	 * @param createdDate  the value for tn_m_role.created_date
	 * @mbg.generated  Sun Aug 12 22:30:57 WIB 2018
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
}