package com.patelki.map;

import com.patelki.domain.TnMCity;
import com.patelki.domain.TnMCityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface TnMCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    long countByExample(TnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int deleteByExample(TnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int insert(TnMCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int insertSelective(TnMCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    List<TnMCity> selectByExample(TnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    TnMCity selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByExampleSelective(@Param("record") TnMCity record, @Param("example") TnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByExample(@Param("record") TnMCity record, @Param("example") TnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByPrimaryKeySelective(TnMCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_city
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByPrimaryKey(TnMCity record);
}