package com.patelki.map;

import com.patelki.domain.TnMLevelManagement;
import com.patelki.domain.TnMLevelManagementExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface TnMLevelManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    long countByExample(TnMLevelManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int deleteByExample(TnMLevelManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int deleteByPrimaryKey(Integer levelManagementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int insert(TnMLevelManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int insertSelective(TnMLevelManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    List<TnMLevelManagement> selectByExample(TnMLevelManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    TnMLevelManagement selectByPrimaryKey(Integer levelManagementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByExampleSelective(@Param("record") TnMLevelManagement record, @Param("example") TnMLevelManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByExample(@Param("record") TnMLevelManagement record, @Param("example") TnMLevelManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByPrimaryKeySelective(TnMLevelManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_level_management
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByPrimaryKey(TnMLevelManagement record);
}