package com.patelki.map;

import com.patelki.domain.TnMRole;
import com.patelki.domain.TnMRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface TnMRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    long countByExample(TnMRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int deleteByExample(TnMRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int insert(TnMRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int insertSelective(TnMRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    List<TnMRole> selectByExample(TnMRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    TnMRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByExampleSelective(@Param("record") TnMRole record, @Param("example") TnMRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByExample(@Param("record") TnMRole record, @Param("example") TnMRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByPrimaryKeySelective(TnMRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tn_m_role
     *
     * @mbg.generated Sat Aug 11 20:55:03 WIB 2018
     */
    int updateByPrimaryKey(TnMRole record);
}