package com.patelki.map;

import com.patelki.domain.TnPUserLogin;
import com.patelki.domain.TnPUserLoginExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface TnPUserLoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	long countByExample(TnPUserLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	int deleteByExample(TnPUserLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	int deleteByPrimaryKey(Integer userLoginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	int insert(TnPUserLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	int insertSelective(TnPUserLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */List<TnPUserLogin> selectByExample(TnPUserLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	TnPUserLogin selectByPrimaryKey(Integer userLoginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */int updateByExampleSelective(@Param("record") TnPUserLogin record,@Param("example") TnPUserLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */int updateByExample(@Param("record") TnPUserLogin record,@Param("example") TnPUserLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	int updateByPrimaryKeySelective(TnPUserLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tn_p_user_login
	 * @mbg.generated  Sat Aug 11 21:14:01 WIB 2018
	 */
	int updateByPrimaryKey(TnPUserLogin record);
}